# Disabled for now, as there is not too much information how to get rebar3 and travis to play nice

sudo: false
language: erlang
install: "true"
otp_release:
  - 18.0
  - 17.0
script: "./rebar3 ct"
branches:
  only:
    - master
